#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmsh -3 -o ring.msh ring.geo
runApplication gmshToFoam ring.msh
runApplication changeDictionary
cp -r 0.org 0
runApplication topoSet
