#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# runApplication gmsh - tube.geo
runApplication gmshToFoam tube.msh
runApplication topoSet
runApplication createPatch -overwrite
